spring.application.name=showroom
secretKey=hutech2026
mysql.host=localhost
mysql.port=3306
mysql.username=root
mysql.password=root
mysql.database=showroom
upload.dir=uploads
uploadsFolder=uploads
spring.servlet.multipart.max-file-size=10MB
